#!/usr/bin/env bash

set -o errexit
set -o errtrace
set -o nounset
set -o pipefail
# set -o xtrace

git-create-update() {
	curl https://raw.githubusercontent.com/dryvenn/scripts/master/git-create-update | bash -s $@
}

git-create-update ~/.scripts https://github.com/dryvenn/scripts
