#!/usr/bin/env bash

useradd -m yves
echo "yves:yves" | chpasswd
chsh yves -s /bin/bash
gpasswd -a yves sudo
gpasswd -a yves tty
gpasswd -a yves dialout
gpasswd -a yves plugdev
yes '' | su yves -c 'ssh-keygen'
su yves -c 'curl https://raw.githubusercontent.com/dryvenn/scripts/master/push-conf | bash -s localhost'

echo "Done. Don't forget to change your password."
