#!/usr/bin/env bash

set -o errexit
set -o errtrace
set -o nounset
set -o pipefail
#set -o xtrace

blue() {
	echo -e "\e[1m\e[34m$@\e[0m"
}

error=0

for dir in $(ls -d */.git | xargs dirname)
do
	pushd $dir &> /dev/null
	blue "[$dir]"
	git $@ || error=$?
	popd &> /dev/null
done

exit $error
