#!/usr/bin/env bash

set -o errexit
set -o errtrace
set -o nounset
set -o pipefail
#set -o xtrace

WD=$(pwd)
SD=$(dirname $(readlink -e $0))

err() {
	1>&2 echo "$*"
}

usage() {
	1>&2 cat <<- EOF
	Usage: > $(basename $0) <game_id>
	EOF
	exit 1
}
[ $# -ne 1 ] && usage

game_id="$1"
base_url="https://www.playdiplomacy.com"

img_name="playdiplomacy_${game_id}.png"
img_path=$(curl -s "$base_url/game_play_details.php?game_id=$game_id" |
	grep $game_id | grep '<img' | cut -d "'" -f 2)

curl -s -o "$img_name" "$base_url/$img_path"

echo "$PWD/$img_name"
