#!/usr/bin/env bash

set -o errexit
set -o errtrace
set -o nounset
set -o pipefail
#set -o xtrace

#dtb=arch/arm/boot/dts/armada-xp-gp.dtb
#dtb=arch/arm/boot/dts/armada-xp-db.dtb
#dtb=arch/arm/boot/dts/armada-xp-db-dxbc2.dtb
dtb=arch/arm/boot/dts/tagada.dtb

cd $(dirname $(readlink -e $0))

cat arch/arm/boot/zImage $dtb > zImage_dtb
mkimage -A arm -O linux -T kernel -C none -a 0x8000 -e 0x8000 -d zImage_dtb uImage_dtb
echo $(readlink -e uImage_dtb)
