#!/usr/bin/env bash

set -o errexit
set -o errtrace
set -o nounset
set -o pipefail
# set -o xtrace

for host in $@
do
	rsync -azh ~/.config $host:
	rsync -azh ~/.scripts $host:
	rsync -azh ~/.*_local $host:
	ssh $host .config/install
done
