#!/usr/bin/env bash

set -o errexit
set -o errtrace
set -o nounset
set -o pipefail
# set -o xtrace

for host in $@
do
	ssh $host 'curl https://raw.githubusercontent.com/dryvenn/config/master/_install | bash'
	ssh $host 'curl https://raw.githubusercontent.com/dryvenn/scripts/master/_install | bash'
done
