#!/usr/bin/env bash

set -o errexit
set -o errtrace
set -o nounset
set -o pipefail
#set -o xtrace

cd ~

for host in $@
do
	rsync -avzh .config $host:
	rsync -avzh .scripts $host:
	rsync -avzh .*_local $host:
	ssh $host .config/install
done
