#!/usr/bin/env bash

set -e

prop="Device Enabled"

id=$(xinput list | grep -i "Synaptics TouchPad" | cut -f 2 | grep -Eo "[[:digit:]]*")

if [ ! "$id" ]
then
	echo "Could not find TouchPad ID..."
	xinput list
	exit 1
fi

state=$(xinput list-props $id | grep "$prop" | cut -f 3)

xinput set-prop $id "$prop" $((($state + 1) % 2))
