#!/usr/bin/env bash

set -o errexit
set -o errtrace
set -o nounset
set -o pipefail
#set -o xtrace

usage() {
	1>&2 cat <<- EOF
	Usage: > $(basename $0)
	EOF
	exit 1
}
[ $# -ne 0 ] && usage

kak=$(readlink -e $(which kak))
kak_repo=$(git -C $(dirname $kak) rev-parse --show-toplevel)
cd $kak_repo

git fetch origin
tag=$(git tag | grep -E 'v[[:digit:]]{4}\.[[:digit:]]{2}\.[[:digit:]]{2}' | tail -n 1)
git checkout $tag
debug=no version=$(git describe --tags HEAD) make -C src/ -j$(nproc)
